export interface YoloHealthTest {
  id: number;
  name: string;
  symptoms: string[];
  description: string;
  parameters: string[];
  timeToResults: string;
  category: string;
  deviceCapability: boolean;
}

export const YOLO_HEALTH_TESTS: YoloHealthTest[] = [
  {
    id: 1,
    name: "12-Lead ECG",
    symptoms: ["chest pain", "palpitations", "shortness of breath", "dizziness", "fainting"],
    description: "Electrocardiogram measuring electrical activity of the heart",
    parameters: ["Heart Rate", "Rhythm", "QT Interval", "ST Segment", "PR Interval", "QRS Duration", "Heart Rate Variability", "Atrial Fibrillation Detection"],
    timeToResults: "Immediate",
    category: "cardiovascular",
    deviceCapability: true,
  },
  {
    id: 2,
    name: "Blood Pressure Monitoring",
    symptoms: ["headache", "blurred vision", "chest discomfort", "shortness of breath"],
    description: "Measurement of systolic and diastolic blood pressure",
    parameters: ["Systolic Pressure", "Diastolic Pressure", "Mean Arterial Pressure", "Pulse Pressure"],
    timeToResults: "Immediate",
    category: "vital signs",
    deviceCapability: true,
  },
  {
    id: 3,
    name: "Blood Glucose Testing",
    symptoms: ["excessive thirst", "frequent urination", "fatigue", "blurred vision"],
    description: "Measures blood glucose levels for diabetes screening",
    parameters: ["Fasting Glucose", "Random Glucose", "Post-Prandial Glucose"],
    timeToResults: "5-10 minutes",
    category: "metabolic",
    deviceCapability: true,
  },
  {
    id: 4,
    name: "Lipid Panel",
    symptoms: ["family history of heart disease", "chest pain", "xanthomas"],
    description: "Comprehensive cholesterol and triglyceride measurement",
    parameters: ["Total Cholesterol", "HDL Cholesterol", "LDL Cholesterol", "Triglycerides", "VLDL Cholesterol", "Cholesterol Ratio"],
    timeToResults: "24-48 hours",
    category: "metabolic",
    deviceCapability: true,
  },
  {
    id: 5,
    name: "Complete Blood Count",
    symptoms: ["fatigue", "weakness", "shortness of breath", "frequent infections"],
    description: "Measures red blood cells, white blood cells, and platelets",
    parameters: ["White Blood Cell Count", "Red Blood Cell Count", "Hemoglobin", "Hematocrit", "Platelets", "Mean Corpuscular Volume", "Mean Corpuscular Hemoglobin", "Red Cell Distribution Width"],
    timeToResults: "24 hours",
    category: "blood",
    deviceCapability: true,
  },
  {
    id: 6,
    name: "Thyroid Panel",
    symptoms: ["weight gain", "fatigue", "cold sensitivity", "hair loss", "mood changes"],
    description: "Evaluates thyroid function with TSH and thyroid hormones",
    parameters: ["TSH", "Free T3", "Free T4", "Total T3", "Total T4", "TPO Antibodies", "Thyroglobulin Antibodies"],
    timeToResults: "24-48 hours",
    category: "endocrine",
    deviceCapability: true,
  },
  {
    id: 7,
    name: "Kidney Function Tests",
    symptoms: ["swelling in legs", "dark urine", "foamy urine", "fatigue"],
    description: "Evaluates kidney function and glomerular filtration rate",
    parameters: ["Creatinine", "BUN", "GFR", "BUN/Creatinine Ratio", "Uric Acid"],
    timeToResults: "24 hours",
    category: "renal",
    deviceCapability: true,
  },
  {
    id: 8,
    name: "Liver Function Tests",
    symptoms: ["jaundice", "abdominal pain", "dark urine", "pale stools"],
    description: "Assesses liver health and function",
    parameters: ["AST", "ALT", "ALP", "Total Bilirubin", "Direct Bilirubin", "Indirect Bilirubin", "Albumin", "Total Protein"],
    timeToResults: "24 hours",
    category: "hepatic",
    deviceCapability: true,
  },
  {
    id: 9,
    name: "Hemoglobin A1C",
    symptoms: ["excessive thirst", "frequent urination", "fatigue", "weight loss"],
    description: "3-month average of blood glucose levels for diabetes monitoring",
    parameters: ["HbA1c Percentage", "eAG (estimated Average Glucose)"],
    timeToResults: "24-48 hours",
    category: "metabolic",
    deviceCapability: true,
  },
  {
    id: 10,
    name: "Troponin Testing",
    symptoms: ["chest pain", "shortness of breath", "nausea", "palpitations"],
    description: "Detects cardiac muscle damage from heart attack",
    parameters: ["High-Sensitivity Troponin I", "High-Sensitivity Troponin T", "Troponin Complex"],
    timeToResults: "1-3 hours",
    category: "cardiovascular",
    deviceCapability: true,
  },
  {
    id: 11,
    name: "B-Type Natriuretic Peptide",
    symptoms: ["shortness of breath", "fatigue", "swelling", "weight gain"],
    description: "Screens for heart failure and ventricular dysfunction",
    parameters: ["BNP Level", "NT-proBNP Level"],
    timeToResults: "1-2 hours",
    category: "cardiovascular",
    deviceCapability: true,
  },
  {
    id: 12,
    name: "Pulse Oximetry",
    symptoms: ["shortness of breath", "chest pain", "cyanosis", "wheezing"],
    description: "Measures blood oxygen saturation and heart rate",
    parameters: ["SpO2", "Oxygen Saturation", "Pulse Rate", "Perfusion Index"],
    timeToResults: "Immediate",
    category: "vital signs",
    deviceCapability: true,
  },
  {
    id: 13,
    name: "Body Composition Analysis",
    symptoms: ["weight gain", "obesity", "metabolic concerns"],
    description: "Measures body mass and composition metrics",
    parameters: ["BMI", "Body Fat Percentage", "Muscle Mass", "Lean Body Mass", "Bone Density", "Water Weight Percentage", "Metabolic Age"],
    timeToResults: "Immediate",
    category: "vital signs",
    deviceCapability: true,
  },
  {
    id: 14,
    name: "Body Temperature",
    symptoms: ["fever", "chills", "fatigue", "malaise"],
    description: "Measures core body temperature",
    parameters: ["Temperature (Celsius)", "Temperature (Fahrenheit)", "Temperature Status"],
    timeToResults: "Immediate",
    category: "vital signs",
    deviceCapability: true,
  },
  {
    id: 15,
    name: "Respiratory Rate",
    symptoms: ["shortness of breath", "chest pain", "rapid breathing", "wheezing"],
    description: "Measures the number of breaths per minute",
    parameters: ["Breaths Per Minute", "Respiratory Pattern", "Breathing Regularity"],
    timeToResults: "Immediate",
    category: "vital signs",
    deviceCapability: true,
  },
  {
    id: 16,
    name: "C-Reactive Protein",
    symptoms: ["inflammation", "fever", "joint pain", "infection"],
    description: "Measures inflammation marker for infection or disease",
    parameters: ["CRP Level", "High-Sensitivity CRP", "CRP Status"],
    timeToResults: "24 hours",
    category: "immune",
    deviceCapability: true,
  },
  {
    id: 17,
    name: "Electrolyte Panel",
    symptoms: ["muscle weakness", "cramping", "confusion", "cardiac arrhythmias"],
    description: "Measures essential electrolyte levels",
    parameters: ["Sodium", "Potassium", "Chloride", "Bicarbonate", "Anion Gap"],
    timeToResults: "24 hours",
    category: "metabolic",
    deviceCapability: true,
  },
  {
    id: 18,
    name: "Calcium and Phosphate",
    symptoms: ["bone pain", "muscle weakness", "paresthesias"],
    description: "Evaluates bone health and mineral metabolism",
    parameters: ["Total Calcium", "Ionized Calcium", "Phosphate", "Calcium-Phosphate Ratio", "Magnesium"],
    timeToResults: "24 hours",
    category: "metabolic",
    deviceCapability: true,
  },
  {
    id: 19,
    name: "Vitamin B12 and Folate",
    symptoms: ["fatigue", "numbness", "memory issues", "depression"],
    description: "Screens for B vitamin deficiencies",
    parameters: ["Vitamin B12", "Folate Level", "Methylmalonic Acid", "Homocysteine"],
    timeToResults: "24-48 hours",
    category: "metabolic",
    deviceCapability: true,
  },
  {
    id: 20,
    name: "Iron Studies",
    symptoms: ["fatigue", "weakness", "shortness of breath"],
    description: "Evaluates iron status and anemia",
    parameters: ["Serum Iron", "TIBC", "Ferritin", "Transferrin Saturation", "UIBC"],
    timeToResults: "24 hours",
    category: "blood",
    deviceCapability: true,
  },
];

export default YOLO_HEALTH_TESTS;
